apiVersion: v2
name: platform-core
description: Core dependency components for platform helm chart
type: application
version: 1.1.0
appVersion: "1.1.0"
dependencies:
  
  - name: argo-events
    version: 2.4.17
    alias: argo-events
    repository: "https://argoproj.github.io/argo-helm"

  - name: argo-workflows
    version: 0.45.28
    alias: argo-workflows
    repository: "https://argoproj.github.io/argo-helm"

  - name: nats
    version: 1.3.14
    alias: nats
    repository: "https://nats-io.github.io/k8s/helm/charts"

  - name: nack
    version: 0.29.2
    alias: nack
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nack.enabled

  - name: storage-class
    version: 1.0.0
    alias: storage-class
    repository: "file://./charts/storage-class"
    condition: storage-class.enabled

  - name: cloudnative-pg
    version: 0.26.0
    alias: cloudnative-pg
    repository: "https://cloudnative-pg.github.io/charts"

  - name: opensearch-operator
    version: "2.8.0"
    repository: "https://opensearch-project.github.io/opensearch-k8s-operator"
    alias: opensearch-operator

  - name: gpu-operator
    version: v24.9.0
    alias: gpu-operator
    repository: "https://helm.ngc.nvidia.com/nvidia"
    condition: gpu-operator.enabled
  
  - name: keydb
    version: 0.48.0
    alias: keydb
    repository: "https://enapter.github.io/charts/"
    condition: keydb.enabled

  - name: kube-prometheus-stack
    version: "81.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled