{{- if .Values.localModel.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: guardrails-model-svc
  labels:
    app: {{ .Values.localModel.labels.app }}
spec:
  type: {{ .Values.localModel.service.type }}
  selector:
    app: {{ .Values.localModel.labels.app }}
  ports:
    {{- range .Values.localModel.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
    {{- end }}
{{- end }}
