apiVersion: v2
name: enkryptai-stack
description: A Helm chart for Kubernetes
type: application
version: 1.1.13
appVersion: "1.1.13"
dependencies:
  - name: openfga
    version: 0.2.26
    alias: openfga
    repository: "https://openfga.github.io/helm-charts"
