apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redteam-add-task-sensor
  namespace: argo-events
  annotations:
    "helm.sh/hook-weight": "10"
    "helm.sh/hook": post-install, post-upgrade
spec:
  dependencies:
  - eventName: redteam
    eventSourceName: redteam-add-task
    name: redteam-add-task
  eventBusName: redteam-eventbus
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: redteam-add-task
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: redteam-add-task-job-
              namespace: redteam-jobs
            spec:
              tolerations:
              - effect: NoSchedule
                key: app
                operator: Equal
                value: redteaming
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: dedicated
                        operator: In
                        values:
                        - redteaming
              arguments:
                parameters:
                - name: event-data
                  value: '{{"{{.Input.body}}"}}'
              entrypoint: process-order
              templates:
              - container:
                  envFrom:
                  - secretRef:
                      name: redteam-proxy-env-secret
                  image: {{ .Values.sensor.jobImage }}:{{ .Values.sensor.jobversion}}
                  imagePullPolicy: Always
                  command: ["python", "job/job_service_sync.py"]
                  {{- if $.Values.sensor.env }}
                  env:
                    {{- toYaml $.Values.sensor.env | nindent 20 }}
                  {{- end }}
                inputs:
                  parameters:
                  - name: event-data
                name: process-order
      name: argo-workflow-trigger
