apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: redteam-attack-sensor
  namespace: argo-events
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "10"
spec:
  dependencies:
  - eventName: redteam
    eventSourceName: redteam-attack
    name: redteam-attack
  eventBusName: redteam-eventbus
  template:
    serviceAccountName: argo-events-sa
  triggers:
  - template:
      argoWorkflow:
        operation: submit
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: redteam-attack
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: redteam-attack-job-
              namespace: redteam-jobs
            spec:
              tolerations:
              - effect: NoSchedule
                key: app
                operator: Equal
                value: redteaming
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: dedicated
                        operator: In
                        values:
                        - redteaming
              arguments:
                parameters:
                - name: event-data
                  value: '{{"{{.Input.body}}"}}'
              entrypoint: process-order
              templates:
              - container:
                  env:
                  - name: WORKER_TYPE 
                    value: "combined"
                  - name: NATS_URL
                    value: {{ .Values.sensor.natsURL }}
                  - name: IS_PROXY_MODE
                    value: "true"
                  - name: RT_NATS_PAYLOAD
                    value: '{{"{{inputs.parameters.event-data}}"}}'
                  envFrom:
                  - secretRef:
                      name: redteam-proxy-env-secret
                  image: {{ .Values.sensor.jobImage }}:{{ .Values.sensor.jobversion}}
                  imagePullPolicy: Always
                  command: ["python", "job/job_service_sync.py"]
                inputs:
                  parameters:
                  - name: event-data
                name: process-order
      name: argo-workflow-trigger
