apiVersion: v2
name: platform-stack
description: Complete platform infrastructure stack
version: 1.0.2
appVersion: "1.0.2"
dependencies:
  - name: platform-core
    version: 1.0.3
    alias: platform-core
    repository: "file://../platform-core"
