apiVersion: v2
name: platform-stack
description: Complete platform infrastructure stack
version: 1.0.3
appVersion: "1.0.3"
dependencies:
  - name: platform-core
    version: 1.0.4
    alias: platform-core
    repository: "https://enkryptai.github.io/helm-charts"
