apiVersion: v2
appVersion: 1.1.9
dependencies:
- alias: platform-core
  name: platform-core
  repository: https://enkryptai.github.io/helm-charts
  version: 1.1.0
description: Complete platform infrastructure stack
name: platform-stack
version: 1.1.9
