apiVersion: v2
appVersion: 1.1.27
dependencies:
  - alias: platform-core
    name: platform-core
    repository: https://enkryptai.github.io/helm-charts
    version: 1.1.0

  - alias: otel
    name: opentelemetry-collector
    version: "0.138.1"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: otel.enabled

description: Complete platform infrastructure stack
name: platform-stack
version: 1.1.27
