apiVersion: v2
name: platform-stack
description: Complete platform infrastructure stack
version: 1.1.7
appVersion: "1.1.7"
dependencies:
  - name: platform-core
    version: 1.1.0
    alias: platform-core
    repository: "https://enkryptai.github.io/helm-charts"
  - name: opentelemetry-collector
    version: "0.138.1"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    alias: otel
    condition: otel.enabled