apiVersion: v2
name: platform-stack
description: Complete platform infrastructure stack
version: 1.1.8
appVersion: "1.1.8"
dependencies:
  - name: platform-core
    version: 1.1.0
    alias: platform-core
    repository: "https://enkryptai.github.io/helm-charts"
