replicaCount: 1

image:
  repository: 188451452903.dkr.ecr.us-east-1.amazonaws.com/enkryptai-prod/guardrails
  pullPolicy: IfNotPresent
  tag: "prodgr-v0.0.5"

nameOverride: ""
fullnameOverride: "guardrails"

podAnnotations:
  reloader.stakater.com/auto: "true"

podLabels:
  app: guardrails

strategy:
  type: Recreate

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: http

resources:
  requests:
    cpu: 4
    memory: 16Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 90
  timeoutSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 120
  timeoutSeconds: 30

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

externalSecret:
  enabled: true
  secretName: guardrails-env-secret
  secretStoreRefName: enkryptai-clustersecret-store
  repoName: enkryptai/guardrails

env:
  - name: GR_MODELS_MODE
    value: "remote"
  - name: SENTRY_LITELLM_GATEWAY_API_KEY
    value: "sentry-litellm-gateway-secret-key"
  - name: SENTRY_LITELLM_GATEWAY_TIMEOUT
    value: "300"
  - name: SENTRY_LITELLM_GATEWAY_URL
    value: "http://enkryptai-litellm:443"
nodeSelector: {}

tolerations: []

affinity: {}
