replicaCount: 1

image:
  repository: vpcdepoyment.azurecr.io/enkryptai-dev/guardrails
  pullPolicy: IfNotPresent
  tag: "dev"

nameOverride: ""
fullnameOverride: "guardrails"

podAnnotations:
  reloader.stakater.com/auto: "true"

podLabels:
  app: guardrails

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  name: http

resources:
  requests:
    cpu: 4
    memory: 16Gi
  limits:
    nvidia.com/gpu: 1

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 90
  timeoutSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 80
  initialDelaySeconds: 120
  timeoutSeconds: 30

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

externalSecret:
  enabled: true
  secretName: guardrails-env-secret
  secretStoreRefName: enkryptai-clustersecret-store
  repoName: enkryptai/guardrails

nodeSelector: {}

tolerations: []

affinity: {}
