apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: global
  annotations:
    "helm.sh/hook-weight": "15"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}

---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: admin
  annotations:
    "helm.sh/hook-weight": "15"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}

---
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: kibanaserver
  annotations:
    "helm.sh/hook-weight": "15"
    "helm.sh/hook": post-install
spec:
  opensearchCluster:
    name: {{ .Values.clustername }}
