global: 
  platform: aws
  image: 
    registry: vpcdepoyment.azurecr.io
ingresscontroller:
  repository: onprem/ingress-controller
  tag: v1.14.0
webhook:
  repository: onprem/kube-webhook-certgen
  tag: v1.6.4




