apiVersion: v2
name: litellm
description: A Helm chart to deploy Litellm gateway 
type: application
version: 1.0.0
appVersion: "1.0"
home: https://github.com/BerriAI/litellm
sources:
  - https://github.com/BerriAI/litellm
keywords:
  - litellm
  - gateway
  - llm
maintainers:
  - name: Enkrypt AI
    email: dev@enkryptai.com
