{{- $secretName := "grafana-admin-secret" -}}
{{- $ns := .Release.Namespace -}}
{{- $existingSecret := lookup "v1" "Secret" $ns $secretName -}}

{{- if not $existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
type: Opaque
data:
  user: {{ "admin" | b64enc | quote }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
