{{- if .Values.rest.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.rest.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.rest.autoscaling.enabled }}
  replicas: {{ .Values.rest.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.rest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supabase.rest.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "supabase.rest.serviceAccountName" . }}

      volumes:
        - name: rest-secret
          secret:
            secretName: {{ .Values.secret.onprem.name }}

      containers:
        - name: {{ include "supabase.rest.name" $ }}
          image: "{{ .Values.global.registry }}/{{ .Values.rest.image.repository }}:{{ .Values.rest.image.tag | default .Chart.AppVersion }}"
          {{- with .Values.rest.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
     
          env:
            {{- range $key, $value := .Values.rest.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}


            - name: DB_PASSWORD_FILE
              value: "/secrets/dbpassword"

            - name: DB_PASSWORD_ENC_FILE
              value: "/secrets/dbpassword"

            - name: DB_NAME_FILE
              value: "/secrets/dbdatabase"

            - name: PGRST_JWT_SECRET_FILE
              value: "/secrets/secretjwt"

            - name: PGRST_APP_SETTINGS_JWT_SECRET_FILE
              value: "/secrets/secretjwt"


            {{- if .Values.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}


            - name: PGRST_DB_URI
              value: "$(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD_ENC)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode=$(DB_SSL)"

          volumeMounts:
            - name: rest-secret
              mountPath: /secrets
              readOnly: true

{{- end }}
