{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-superuser-secret
  annotations:
    "helm.sh/hook-weight": "2"

spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: enkryptai-clustersecret-store
    kind: ClusterSecretStore
  target:
    name: postgres-superuser-secret
  data:
    - secretKey: username
      remoteRef:
        key: enkryptaivpc/supabase-postgres
        property: username
    - secretKey: password
      remoteRef:
        key: enkryptaivpc/supabase-postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: superuser-secret
  annotations:
    "helm.sh/hook-weight": "2"

spec:
  refreshInterval: "15m"
  secretStoreRef:
    name: enkryptai-clustersecret-store
    kind: ClusterSecretStore
  target:
    name: superuser-secret
  data:
    - secretKey: username
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: username
    - secretKey: password
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: password
    - secretKey: DB_HOST
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: DB_PORT
    - secretKey: DB_USER
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: DB_USER
    - secretKey: DB_NAME
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: DB_NAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: DB_PASSWORD
    - secretKey: grant-admin.sql
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: grant-admin.sql
    - secretKey: kong.sql
      remoteRef:
        key: enkryptaivpc/supabase-admin
        property: kong.sql
{{- end }}
