{{- if .Values.meta.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.meta.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.meta.autoscaling.enabled }}
  replicas: {{ .Values.meta.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.meta.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "supabase.meta.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "supabase.meta.serviceAccountName" . }}

      volumes:
        - name: meta-secret
          secret:
            secretName: {{ .Values.secret.onprem.name }}

      containers:
        - name: {{ include "supabase.meta.name" $ }}
          image: "{{ .Values.global.registry }}/{{ .Values.meta.image.repository }}:{{ .Values.meta.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.meta.image.pullPolicy }}

          env:
            - name: PG_META_PORT
              value: "8080"

            {{- range $key, $value := .Values.meta.environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- if .Values.db.enabled }}
            - name: DB_HOST
              value: {{ include "supabase.db.fullname" . }}
            {{- end }}


            - name: DB_PASSWORD_FILE
              value: "/secrets/dbpassword"
            - name: DB_NAME_FILE
              value: "/secrets/dbdatabase"


            - name: PG_META_DB_HOST
              value: "$(DB_HOST)"
            - name: PG_META_DB_PORT
              value: "$(DB_PORT)"
            - name: PG_META_DB_NAME_FILE
              value: "/secrets/dbdatabase"
            - name: PG_META_DB_USER
              value: "$(DB_USER)"
            - name: PG_META_DB_PASSWORD_FILE
              value: "/secrets/dbpassword"
            - name: PG_META_DB_SSL_MODE
              value: "$(DB_SSL)"

          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.meta.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: meta-secret
              mountPath: /secrets
              readOnly: true
{{- end }}
