replicaCount: 2

image:
  repository: 188451452903.dkr.ecr.us-east-1.amazonaws.com/test/redteaming-test
  pullPolicy: Always
  tag: "v1.0.0"

nameOverride: ""
fullnameOverride: "redteam-proxy"

podAnnotations:
  reloader.stakater.com/auto: "true"

podLabels:
  app: redteam-proxy

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 50%
    maxUnavailable: 50%

service:
  type: ClusterIP
  port: 9091
  targetPort: 8443
  name: http

env:
  - name: NATS_URL
    value: "nats://nats:4222"
  - name: IS_PROXY_MODE
    value: "true"

resources:
  requests:
    cpu: 100m
    memory: 300Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8443
  initialDelaySeconds: 90
  timeoutSeconds: 10

readinessProbe:
  enabled: true
  httpGet:
    path: /health
    port: 8443
  initialDelaySeconds: 30
  timeoutSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

externalSecret:
  enabled: true
  secretName: redteam-proxy-env-secret
  secretStoreRefName: enkryptai-clustersecret-store
  repoName: enkryptai/redteam-proxy

nodeSelector: {}

tolerations: []

affinity: {}
